### PR TITLE
add simple script to print primes up to n

### PR DESCRIPTION
**Pull request by bearnard**
- A simple script to generate a list of prime numbers up to n

We start with the https://en.wikipedia.org/wiki/Prime_number definition

```

A prime number (or a prime) is a natural number greater than 1 that has no positive divisors other than 1 and itself.

```

### CODE REVIEW

**Comment by bearnard** [comment]
@chrisgeo

**Comment by chrisgeo** [comment]
Awesome, thanks @bearnard looking great so far.

**Comment by bearnard** [comment]
@chrisgeo 

I improved on the algorithm a bit after reading: https://en.wikipedia.org/wiki/Primality_test#Python_implementation

**Comment by chrisgeo** [comment]
This is great! Definitely ready for a merge.

**Pull request merged**
